## Travis CI Integration

language: c

env:
  global:
  - secure: CVZbuPPT+6b6gVhuqa7HUFZNs2QlPGdhRBtRYgjGniZKyTBPuB6ofOjhupBcMSmVZyHES6m0GcJNUxSUe726je6nB+8jmvmhoMtUpMmsR/uG53NntCRlaUjWtHVLQEOgNrFKzHYWxsBxztosERaqay28V9okLJyYkLZCB2QIngY=
  - secure: KRq/zSKJLFlYEf4NBNnm51A9ceDOOEmClu63TU5x7z8p4PCIHDcYF3GwpRi/O/WpkxKZL8o37+Qat8z2cyxKi4fZpHVqJxRGYKXItopj9oV2zTvEMXHxXsJixC2exejTWEBU5CtkTxkLOmcb6qkHYhuHTd2hxcjkJQwl9m2WXPs=
  - secure: nIxBDSH5efqVRv+GMqYG2Nx9gz3rvIz3Wsm1rdu5G2knhWYaMdrrHpYo/0JpKKwx9sK5wL+tx/dLilgfbS9RDIFMczKULyC8YSEliPReYQq5VXUpKvpiJZgBhE5Rl2TMy+WdxcgA1mgXZtLlMcWFJF+0bJIKOhkUeKZJxu2KT6I=
  - secure: EBpkujWNFVDWZVgIJNJAjqFuMRh+w5ASfIm0lrumSSBSicQrmaxUb8+ScGNgA9qra2HwK6RBrJwcKnZNl6HsznvTnBYGNF0bNEEZxGERIgSkwcW83JudxUZOeYly3tqQwFzMQHnJleaFf2Oq4Lqo78FoTRK7HA1Hg7fxKRzSZz8=
    
install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console
script:
  - xbuild /p:Configuration=Release Rainbow.sln
  
after_success:
- wget https://www.dropbox.com/s/fp1gpiyb1ew0tz5/dropbox_uploader.sh?dl=1 -O ./dropbox_uploader.sh
- chmod +x ./dropbox_uploader.sh
- echo $APPKEY >> dropbox_config
- echo $APPSECRET >> dropbox_config
- echo $ACCESS_LEVEL >> dropbox_config
- echo $OAUTH_ACCESS_TOKEN >> dropbox_config
- echo $OAUTH_ACCESS_TOKEN_SECRET >> dropbox_config
- zip rainbow_win32_bin_dev.zip /home/travis/build/marco-calautti/Rainbow/Rainbow.App/bin/v3.5/Release/*.exe /home/travis/build/marco-calautti/Rainbow/Rainbow.App/bin/v3.5/Release/*.dll
- ./dropbox_uploader.sh upload rainbow_win32_bin_dev.zip AutomatedBuilds/Rainbow/rainbow_win32_bin_dev.zip
